# Generated by Django 3.2.8 on 2021-11-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
                ('icono', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Superheroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('icono', models.URLField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('muerto', models.BooleanField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroWeb.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Superpoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
                ('superheroe', models.ManyToManyField(to='heroWeb.Superheroe')),
            ],
        ),
    ]
