# Generated by Django 3.2.8 on 2021-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='id_api',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
