# Generated by Django 3.2.8 on 2021-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroWeb', '0002_superheroe_id_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='base',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
